// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPerspective struct {
	Text string `json:"text"`
}

type Perspective struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
}
